<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <!-- package information -->
    <name>ximea_camera</name>
    <version>1.0.1</version>
    <description>ros2 driver for ximea cameras</description>

    <!-- authour information -->
    <author email="c25wang@uwaterloo.ca">Carlos Wang</author>
    <maintainer email="michal.antkiewicz@uwaterloo.ca">Michal Antkiewicz</maintainer>

    <license>MIT</license>

    <!-- build tool information  -->
    <buildtool_depend>ament_cmake</buildtool_depend>

    <!-- depends -->
    <depend>rclcpp</depend>
    <depend>rclcpp_components</depend>
    <depend>sensor_msgs</depend>
    <depend>image_transport</depend>
    <depend>camera_info_manager</depend>
    <depend>std_msgs</depend>
    <depend>libopencv-dev</depend>
    <depend>rosidl_default_generators</depend>
    <depend>diagnostic_updater</depend>

    <!-- The export tag contains other, unspecified, tags -->
    <export>
      <build_type>ament_cmake</build_type>
    </export>
</package>
